from __future__ import annotations

from datetime import date, datetime, timezone
from pathlib import Path

import structlog

from second_brain.core.models import ProcessedContent, RawContent, RunStats

logger = structlog.get_logger()


class DailyNoteWriter:
    def __init__(self, vault_path: Path) -> None:
        self.vault_path = vault_path
        self.daily_dir = vault_path / "01-Daily"

    def write(
        self,
        stats: RunStats,
        new_notes: list[tuple[RawContent, ProcessedContent, Path]],
        run_date: date | None = None,
    ) -> Path:
        today = run_date or date.today()
        note_path = self.daily_dir / f"{today:%Y-%m-%d}.md"
        self.daily_dir.mkdir(parents=True, exist_ok=True)
        note_path.write_text(self._render(today, stats, new_notes), encoding="utf-8")
        logger.info("daily_note_written", path=str(note_path))
        return note_path

    def _render(
        self,
        day: date,
        stats: RunStats,
        new_notes: list[tuple[RawContent, ProcessedContent, Path]],
    ) -> str:
        duration = stats.duration_seconds
        duration_str = f"{int(duration // 60)}m {int(duration % 60)}s" if duration >= 60 else f"{duration:.1f}s"
        provider_str = " | ".join(f"{k} ({v})" for k, v in stats.provider_counts.items())

        lines = [
            f"# {day:%Y-%m-%d}",
            "",
            "## Pipeline Summary",
            f"- Processed: {stats.sources_processed} sources in {duration_str}",
            f"- Notes created: {stats.notes_created} | Updated: {stats.notes_updated} | Skipped: {stats.notes_skipped} (dupe)",
            f"- Tokens used: {stats.tokens_used:,} | Cost: ${stats.cost_usd:.4f}",
            f"- Provider: {provider_str or 'none'}",
            "",
        ]

        if new_notes:
            lines.append("## New Notes")
            for raw, processed, note_path in new_notes:
                note_name = note_path.stem
                summary_short = processed.summary.splitlines()[0][:80] if processed.summary else raw.title
                lines.append(f"- [[{note_name}]] — {summary_short}")
            lines.append("")

        if stats.failed_count:
            lines.extend(["## Failures", f"- {stats.failed_count} sources failed — see pipeline log", ""])

        if stats.notes_fallback:
            lines.extend(
                [
                    "## Inbox (needs processing)",
                    f"- {stats.notes_fallback} items written to 00-Inbox (LLM unavailable)",
                    "",
                ]
            )

        # Collect top insights from processed notes
        all_insights: list[str] = []
        for _, processed, _ in new_notes:
            all_insights.extend(processed.key_insights[:2])

        if all_insights:
            lines.append("## Top Insights")
            for i, insight in enumerate(all_insights[:5], 1):
                lines.append(f"{i}. {insight}")
            lines.append("")

        lines.extend(["---", f"*Generated by Second Brain OS at {datetime.now(timezone.utc):%Y-%m-%dT%H:%M:%SZ}*"])
        return "\n".join(lines)
