from __future__ import annotations

from pathlib import Path


PROJECT_FOLDERS = [
    "01-ContextForge",
    "02-RAGBench-Pro",
    "03-AgentOrchestra",
    "04-MemoryOS",
    "05-AutoResearch-v2",
    "06-MCPForge-Suite",
    "07-MCPGuard",
    "08-EvalEngine",
    "09-GuardStack",
    "10-LLMScope",
    "11-GraphRAG-Engine",
    "12-PromptOpt",
    "13-ToolForge",
    "14-StructOut",
    "15-SemanticRouter",
    "16-DocIQ",
    "17-SynthGen",
    "18-SelfHeal",
    "19-RedTeamKit",
    "20-LiveRAG",
    "21-SemanticCache",
    "22-BrowserAgent",
    "23-SQLAgent-Pro",
    "24-DebateArena",
]


def scaffold_vault(vault_path: Path) -> list[Path]:
    folders = [
        "00-Inbox",
        "01-Daily/templates",
        "02-Projects",
        *[f"02-Projects/{folder}" for folder in PROJECT_FOLDERS],
        "03-Research/context-engineering",
        "03-Research/rag-architectures",
        "03-Research/multi-agent-systems",
        "03-Research/mcp-protocol",
        "03-Research/evaluation-frameworks",
        "03-Research/job-market",
        "04-Resources/videos",
        "04-Resources/articles",
        "04-Resources/repos",
        "05-Learning",
        "06-Career/target-companies",
        "06-Career/job-postings",
        "06-Career/interview-prep",
        "07-Meta",
    ]
    created_paths: list[Path] = []
    for folder in folders:
        path = vault_path / folder
        path.mkdir(parents=True, exist_ok=True)
        created_paths.append(path)

    moc = vault_path / "07-Meta" / "MOC-Home.md"
    if not moc.exists():
        moc.write_text("# Map of Content\n\nGenerated by `sbo vault setup`\n", encoding="utf-8")

    overview = vault_path / "02-Projects" / "00-Portfolio-Overview.md"
    if not overview.exists():
        overview.write_text(
            "# Portfolio Overview\n\n24 AI engineering projects — 10 weeks.\n",
            encoding="utf-8",
        )

    return created_paths
